server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wy_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.186.134
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: 127.0.0.1
      database: wy_db
      port: 27017
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 3GB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty
      insert-strategy: not_empty
      logic-not-delete-value: 1
      logic-delete-value: 0
  mapper-locations: classpath:/top/gzk/wy/web/*/mapper/xml/*.xml


#jwt配置
jwt:
  secret: gaozhikunhahaha
  #30分钟过期
  expiration: 1800000